services:
  - type: web
    name: SUML_Projekt
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --sercer.port $PORT --server.address 0.0.0.0